# Generated by Django 6.0.6 on 2026-07-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_color_product_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_oz',
        ),
        migrations.AddField(
            model_name='product',
            name='fitment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_year_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_year_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('wheels', 'Wheels'), ('tires', 'Tires'), ('suspension', 'Suspension'), ('exhaust', 'Exhaust'), ('performance', 'Performance'), ('lighting', 'Lighting'), ('audio', 'Audio'), ('exterior', 'Exterior'), ('interior', 'Interior'), ('detailing', 'Detailing'), ('merchandise', 'Merchandise'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
