export const aircraftsData = [
  {
    registration: "AP-786",
    model: "Boeing 737-800 (NG)",
    flightNum: "FJL205",
    progressVal: "125px",
    departure: "OPKC",
    arrival: "OPIS",
  },
  {
    registration: "AP-782",
    model: "Airbus A320-200",
    flightNum: "FJL235",
    progressVal: "85px",
    departure: "OPKC",
    arrival: "OPIS",
  },
  {
    registration: "AP-724",
    model: "Airbus A320-200",
    flightNum: "FJL307",
    progressVal: "150px",
    departure: "OPKC",
    arrival: "OOMS",
  },
  {
    registration: "AP-712",
    model: "Airbus A320-200",
    flightNum: "FJL236",
    progressVal: "23px",
    departure: "OPIS",
    arrival: "OTHH",
  },
  {
    registration: "AP-736",
    model: "Airbus A320-200",
    flightNum: "FJL307",
    progressVal: "150px",
    departure: "OPKC",
    arrival: "OOMS",
  },
  {
    registration: "AP-788",
    model: "Boeing 737-800 (NG)",
    flightNum: "FJL420",
    progressVal: "100px",
    departure: "OPLA",
    arrival: "OOMS",
  },
  {
    registration: "AP-758",
    model: "Airbus A320-200",
    flightNum: "FJL510",
    progressVal: "182px",
    departure: "OPKC",
    arrival: "OMDB",
  },
];
