export const routeData = [
  {
    flightNum: "FJL205",
    registration: "AP-786",
    model: "Boeing 737-800 (NG)",
    departure: "OPKC",
    arrival: "OPIS",
    depTime: "00:30",
    arrTime: "02:30",
    status: "active",
  },
  {
    flightNum: "FJL235",
    registration: "AP-786",
    model: "Airbus A320-200",
    departure: "OPIS",
    arrival: "OOMS",
    depTime: "03:30",
    arrTime: "06:40",
    status: "active",
  },
  {
    flightNum: "FJL205",
    registration: "AP-786",
    model: "Boeing 737-800 (NG)",
    departure: "OPKC",
    arrival: "OPIS",
    depTime: "00:30",
    arrTime: "02:30",
    status: "active",
  },
  {
    flightNum: "FJL205",
    registration: "AP-786",
    model: "Boeing 737-800 (NG)",
    departure: "OPKC",
    arrival: "OPIS",
    depTime: "00:30",
    arrTime: "02:30",
    status: "active",
  },
  {
    flightNum: "FJL205",
    registration: "AP-786",
    model: "Boeing 737-800 (NG)",
    departure: "OPKC",
    arrival: "OPIS",
    depTime: "00:30",
    arrTime: "02:30",
    status: "active",
  },
];
