# Generated by Django 6.0.6 on 2026-07-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_meta_description_service_meta_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AddField(
            model_name='service',
            name='compatible_vehicle_types',
            field=models.CharField(blank=True, help_text='Example: coupe, sedan, SUV, truck', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_vehicle_dropoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_at_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('window_tint', 'Window Tint'), ('vinyl_wrap', 'Vinyl Wrap'), ('ceramic_coating', 'Ceramic Coating'), ('paint_protection_film', 'Paint Protection Film'), ('detailing', 'Detailing'), ('wheel_tire', 'Wheel & Tire'), ('suspension', 'Suspension'), ('performance', 'Performance'), ('audio', 'Audio'), ('lighting', 'Lighting'), ('fabrication', 'Fabrication'), ('other', 'Other')], default='other', max_length=60),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
